name: Build, Test, and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Stop wasting time caching packages / Disable sending usage data to Microsoft
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.0'
      - name: Restore
        working-directory: ./src
        run: dotnet restore
      - name: Build
        working-directory: ./src
        run: dotnet build --no-restore
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_ENVIRONMENT: 'Testing'
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testing
          POSTGRES_PASSWORD: testing
          POSTGRES_DB: testing
        ports:
          - 5433:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.0'
      - name: Restore
        working-directory: ./src
        run: dotnet restore
      - name: Build
        working-directory: ./src
        run: dotnet build --no-restore
      - name: Test
        working-directory: ./src
        run: dotnet test --no-build --verbosity normal --property:WarningLevel=0
  publish:
    needs: test
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_REPO: respondo
      IMAGE_NAME: service.respondo
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login in the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}