name: Build, Test, and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Stop wasting time caching packages / Disable sending usage data to Microsoft
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-rc.1.24452.12'
      - name: Restore
        working-directory: ./src  
        run: dotnet restore
      - name: Build
        working-directory: ./src
        run: dotnet build --no-restore
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_ENVIRONMENT: 'Workflow'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-rc.1.24452.12'
      - name: Test
        working-directory: ./src
        run: dotnet test --verbosity normal
