name: Build, Test, and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  # Stop wasting time caching packages / Disable sending usage data to Microsoft
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-rc.1.24452.12'
      - name: Restore
        working-directory: ./src
        run: dotnet restore
      - name: Build
        working-directory: ./src
        run: dotnet publish -o service --no-restore --configuration Release
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./src
  test:
    needs: build
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_ENVIRONMENT: 'Testing'
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testing
          POSTGRES_PASSWORD: testing
          POSTGRES_DB: testing
        ports:
          - 5433:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-rc.1.24452.12'
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./src
      - name: Test
        working-directory: ./src
        run: dotnet test --configuration Release --no-build --verbosity normal --property:WarningLevel=0
